---
title: "BT2102 Assignment 2"
author: "Howard Lee"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(wordcloud)
library(RColorBrewer)
library(wordcloud2)
library(tm)
library(dplyr)
```


```{r wordcloud, echo=FALSE}

data <- read.csv("olist_order_reviews_dataset.csv", stringsAsFactors = FALSE)
data <- data %>% filter(review_score <= 3)
reviews <- data$review_comment_message
corpus <- Corpus(VectorSource(reviews))
corpus <- tm_map(corpus, content_transformer(tolower)) # Convert to lowercase
corpus <- tm_map(corpus, removeNumbers)               # Remove numbers
corpus <- tm_map(corpus, removePunctuation)           # Remove punctuation
corpus <- tm_map(corpus, removeWords, stopwords("pt")) # Remove Portuguese stopwords
corpus <- tm_map(corpus, stripWhitespace)             # Remove extra whitespace
corpus <- tm_map(corpus, stemDocument, language = "portuguese")

tdm <- TermDocumentMatrix(corpus)
m <- as.matrix(tdm)
word_freq <- sort(rowSums(m), decreasing = TRUE)
words <- names(word_freq)

wordcloud(
  words = words,
  freq = word_freq,
  min.freq = 2,           # Adjust minimum frequency as needed
  max.words = 200,        # Adjust the number of words to display
  random.order = FALSE,   # Words arranged by frequency
  colors = brewer.pal(8, "Dark2") # Color palette
)
```



